version: "3"

services:
  app: &app
    hostname: app
    image: developulse
    stdin_open: true
    tty: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      - PORT=3000
      - SUBMIT_URL=https://imc-hiring-test.azurewebsites.net/Contact/Save
    command: "yarn start"
